# Generated by Django 3.2.8 on 2021-10-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
