# Generated by Django 3.2.8 on 2021-11-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_definition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hara_function',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hara_rationale',
        ),
        migrations.AddField(
            model_name='function',
            name='hara_function',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='function',
            name='hara_rationale',
            field=models.CharField(default='Enter rationale', max_length=250),
        ),
    ]
