# Generated by Django 3.2.8 on 2021-11-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_definition', '0002_auto_20211106_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='hara_rationale',
            field=models.CharField(default='Enter rationale', max_length=250, null=True),
        ),
    ]
