# Generated by Django 3.2.8 on 2021-10-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(default='Enter company description', max_length=250)),
                ('industry', models.CharField(default='', max_length=25, null='False')),
            ],
        ),
    ]
