# Generated by Django 3.2.8 on 2021-10-30 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blackbook', '0002_auto_20211030_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=50),
        ),
    ]
