# Generated by Django 3.2.8 on 2021-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0004_auto_20211030_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
