# Generated by Django 3.2.8 on 2021-11-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0005_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
