# Generated by Django 3.2.8 on 2021-11-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0006_auto_20211106_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
