# Generated by Django 3.2.8 on 2021-11-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0007_remove_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
